### ISSUE TITLE
Finish writing documentation

### ISSUE THREAD

**Issue by graphitemaster** [graphitemaster/redroid#16]
There are various aspects of Redroid that aren't documented and need to be. The front end web interface should be documented on the wiki as an example.

**Comment by ghost** [comment]
Very well Mr Master. I'll do it when I have time.

**Comment by graphitemaster** [comment]
Need documentation of access control. Specifically the access module.

**Comment by graphitemaster** [comment]
Need documentation updates for the system module specifically the addition of `-daemonize` Which can be called to put the bot into a daemon state and release it's handle to the terminal it was launched in.

**Comment by graphitemaster** [comment]
Updated documentation. Once the tipjar command is implemented it will need to be documented. I'm closing this otherwise.
