### ISSUE TITLE
Make SVN module configurable and modular

### ISSUE THREAD

**Issue by ghost** [graphitemaster/redroid#25]
The Subversion repository to monitor is currently defined as a header.

The _svn_ module should be configurable through the configuration file so to allow for multiple Subversion repositories and their associated web viewers.

Would be nice for the Tesseract channel in particular.

**Comment by graphitemaster** [comment]
This can't be implemented yet without support for the hierarchical configuration format stuff I wanted. Ideally modules will load this data from the configuration file of the bot.

**Comment by graphitemaster** [comment]
This is now supported.
